language: android
sudo: true # y tho

env:
  global:
    - COMPILE_SDK_VERSION=27 
    - BUILD_TOOLS_VERSION=27.0.2

android:
  components:
    - tools # Update android-sdk (also called android-sdk-tools)
    - platform-tools
    - tools # Write the second time to update to thes newest as described in the document
    - build-tools-${BUILD_TOOLS_VERSION} # For building
    - android-${COMPILE_SDK_VERSION} # For building
    - extra-android-m2repository # Support library

# whitelist
branches:
  only:
    - kt-n

before_install:
  - chmod +x gradlew
  - echo $unencrypt | gpg --passphrase-fd 0 TGXMods.jks.gpg

script: ./gradlew assembleDebug

install:
  - sdkmanager --list || true # Debug / Observation
  - echo y | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2" #&> /dev/null
  - echo y | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2" #&> /dev/null
  - echo y | sdkmanager 'ndk-bundle'
  - echo y | sdkmanager 'cmake;3.6.4111459'
  - echo y | sdkmanager 'lldb;3.0'
  - echo y | sdkmanager "platforms;android-27"
  - avdmanager --list || true  # Debug / Observation
  
before_deploy:
  - chmod +x scripts/changelog.sh
  - cp $TRAVIS_BUILD_DIR/.keystore $HOME
  - cd app/build/outputs/apk/
  - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/keystore.jks -storepass $storepass -keypass $keypass app-release-unsigned.apk tgxmods
  # Verification
  - jarsigner -verify app-release-unsigned.apk
  - "${ANDROID_HOME}/build-tools/27.0.3/zipalign -v 4 app-debug-unsigned.apk app-debug.apk"

deploy:
  - provider: script
    skip_cleanup: true
    script: "sh scripts/deploy-telegram.sh"
    on:
      branch: kt-n
