language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - extra-google-m2repository
  before_install:
    - yes | sdkmanager "platforms;android-27"
    - if [ `uname -m` = x86_64]; then wget http://dl.google.com/android/ndk/android-ndk-r16b-linux-x86_64.tar.bz2 -O ndk.tgz; else wget http://dl.google.com/android/ndk/android-ndk-r16b-linux-x86.tar.bz2 -O ndk.tgz; fi
    - tar -xf ndk.tgz
    - export ANDROID_NDK_HOME=`pwd`/android-ndk-r16b
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}
